### PR TITLE
Add support for role_user field for Users

### PR DESCRIPTION
**Pull request by Acidity**

### CODE REVIEW

**Comment by lfaraone** [comment]
Travis is sad. Also, I can't figure out what this commit is trying to do?

**Comment by Acidity** [comment]
It looks like the travis error is unrelated? But I can't repro it on my local machine either so...

This is trying to expose the role_user field to users of the client so they may use it as they need.

**Comment by lfaraone** [comment]
OK. Do we want to rename this, since it'll be hard to fix later? (since this attribute is not actually used in the way that "role users" traditionally is used)

**Comment by Acidity** [comment]
Updated

**Pull request merged**
